# Generated by Django 3.2.5 on 2022-05-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_array_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='array',
            name='boby',
            field=models.TextField(blank=True),
        ),
    ]
